#!/bin/bash 
#
# Script to install container networking
#
# Depends on:
# 1. bash-lib-logging
# 2. bash-lib-execmd
#

containerNetworking_install()
{
	local _CONTAINER_NETWORKING_TYPE=$1
	local func="${_CONTAINER_NETWORKING_TYPE}_install"
	if (( $(isFunction ${func}) )); then
		${func}
		if (( $? )); then
			abort "Failed to install [${_CONTAINER_NETWORKING_TYPE}] container networking" 
		else
			log "Successfully installed [${_CONTAINER_NETWORKING_TYPE}] container networking" 
		fi
	else
		log   "Unable to install container networking [${_CONTAINER_NETWORKING_TYPE}]"
		abort "Not yet implemented"
	fi 
}

containerNetworking_prepare_for_reinstall()
{
	:  # Nothing to do 
}

#::END::
