#!/bin/bash 
#
# Script to setup container networking using Cilium
#
# Depends on
#  1. bash-lib-loging
#  2. bash-lib-cmdexe
# 

cilium_setup()
{
	local CILIUM_YAML_URL="https://raw.githubusercontent.com/cilium/cilium/${CILIUM_VERSION}/install/kubernetes/quick-install.yaml"
	exeCmd_asAdminUser "kubectl apply -f ${CILIUM_YAML_URL}" 
}


#::END::
